[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nukem_anchor = "4Mx8JsEfP1pYkddqimqUt3zhP9tBxXJxNg3qtMJTDPVc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/casi/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
